### ISSUE TITLE
biscuit generate fails to handle $EDITOR having arguments already

### ISSUE THREAD

**Issue by marhel** [biscuit-auth/biscuit-cli#19]
Following the instructions in "Create a biscuit token" in the README, the generate command failed.

    > biscuit generate --private-key-file martin-private-key-file
    thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/main.rs:773:42
    note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

I think this is because the code uses the $EDITOR environment variable, but fails to recognize it might already contain arguments.
My $EDITOR is set to `subl -nw`, and it seems biscuit-cli now tries to find an executable named `subl -nw` which obviously fails.

This suspicion seems validated by [line 271 in main.rs](https://github.com/biscuit-auth/biscuit-cli/blob/47349b9bb1a4b0bed077e1ddb48bd26b01fc5985/src/main.rs#L271).

Re-running the command with a atomic $EDITOR works;

    EDITOR=nano biscuit generate --private-key-file martin-private-key-file

However, removing the arguments in $EDITOR does not work for Sublime Text, as the `subl` command spawns a child process and exits immediately unless passed "-w" to wait for the editor window to be closed. If $EDITOR is simply `subl`, the `biscuit generate` command starts an editor window, but continues immediately and reads an empty file.

**Comment by divarvel** [comment]
Ha indeed I used EDITOR naively. I'm pondering the different choices available. Nothing is super satisfying right now
