### ISSUE TITLE
--version is still reporting 0.2.0

### ISSUE THREAD

**Issue by gaelreyrol** [biscuit-auth/biscuit-cli#44]
Hi,

I am updating the biscuit-cli Nix derivation and it seems `--version` option still output `0.2.0`. I think the culprit is [here](https://github.com/biscuit-auth/biscuit-cli/blob/0.4.0/src/cli.rs#L92) but maybe I am wrong.

Regards

**Comment by divarvel** [comment]
You're right, I'll issue a 4.0.1 with the fix

**Comment by divarvel** [comment]
Fixed in #46 https://github.com/biscuit-auth/biscuit-cli/pull/46/files#diff-b2812f19576dd53d0c35b107a322f58a00fce6977f4b5976e1961853982af3ccL99
